name: test_athkar_app
description: "ØªØ·Ø¨ÙŠÙ‚ Ø£Ø°ÙƒØ§Ø± Ø¥Ø³Ù„Ø§Ù…ÙŠØ© Ù„Ù„ØªØ¬Ø±Ø¨Ø©."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # ðŸŒ Ø®Ø·ÙˆØ· ÙˆØ£ÙŠÙ‚ÙˆÙ†Ø§Øª
  google_fonts: ^4.0.4                # Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø®Ø·ÙˆØ· Google
  cupertino_icons: ^1.0.8              # Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª Ù†Ø¸Ø§Ù… iOS

  # ðŸŽ¬ Ø­Ø±ÙƒØ§Øª ÙˆØ§Ù†ØªÙ‚Ø§Ù„Ø§Øª
  animations: ^2.0.11                  # Ø­Ø²Ù…Ø© Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø±ÙƒØ§Øª Ø¬Ù…ÙŠÙ„Ø©
  flutter_staggered_animations: ^1.1.1 # Ø­Ø±ÙƒØ§Øª Ù…Ø±ØªØ¨Ø© Ù„Ù„Ø¹Ù†Ø§ØµØ± Ø¯Ø§Ø®Ù„ List/Grid
  loading_animation_widget: ^1.3.0     # Ø­Ø²Ù…Ø© Ø±Ø³ÙˆÙ… Ù…ØªØ­Ø±ÙƒØ© Ù„Ù„ØªØ­Ù…ÙŠÙ„
  animated_flip_counter: ^0.3.4        # Ø¹Ø¯Ø§Ø¯ Ù…ØªØ­Ø±Ùƒ
  circular_seek_bar: ^1.1.1            # Ø´Ø±ÙŠØ· Ø¨Ø­Ø« Ø¯Ø§Ø¦Ø±ÙŠ Ù„Ù„Ù…Ø³Ø¨Ø­Ø©

  # ðŸ•°ï¸ Ø§Ù„ØªØ¹Ø§Ù…Ù„ Ù…Ø¹ Ø§Ù„ÙˆÙ‚Øª ÙˆØ§Ù„ØªØ§Ø±ÙŠØ®
  intl: ^0.19.0                        # Ø§Ù„ØªØ¹Ø§Ù…Ù„ Ù…Ø¹ ØªÙ†Ø³ÙŠÙ‚Ø§Øª Ø§Ù„ØªØ§Ø±ÙŠØ® ÙˆØ§Ù„ÙˆÙ‚Øª
  hijri: ^3.0.0                        # Ø¯Ø¹Ù… Ø§Ù„ØªÙ‚ÙˆÙŠÙ… Ø§Ù„Ù‡Ø¬Ø±ÙŠ
  hijri_calendar: ^1.0.7+7             # ØªÙ‚ÙˆÙŠÙ… Ù‡Ø¬Ø±ÙŠ Ù…Ø­Ø³Ù‘Ù†

  # ðŸ—‚ï¸ Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø§Ù„Ø© ÙˆØ§Ù„ØªØ®Ø²ÙŠÙ†
  provider: ^6.1.5                     # Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø§Ù„Ø© Ø¨Ø·Ø±ÙŠÙ‚Ø© Ø¨Ø³ÙŠØ·Ø©
  shared_preferences: ^2.1.0           # Ø­ÙØ¸ Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª Ù…Ø­Ù„ÙŠÙ‹Ø§ (ÙƒØ§Ù„ØªÙØ¶ÙŠÙ„Ø§Øª)

  # ðŸš€ Ø§Ù„Ø´Ø§Ø´Ø§Øª Ø§Ù„Ø£ÙˆÙ„ÙŠØ© ÙˆØ§Ù„Ø§Ù†Ø·Ù„Ø§Ù‚
  flutter_onboarding_slider: ^1.0.11   # Ø´Ø±Ø§Ø¦Ø­ Ø§Ù„Ù…Ù‚Ø¯Ù…Ø© (Onboarding)
  another_flutter_splash_screen: ^1.2.1 # Ø´Ø§Ø´Ø© Ø§Ù„Ø¨Ø¯Ø§ÙŠØ© (Splash Screen)
  flutter_native_splash: ^2.4.6        # ØªÙˆÙ„ÙŠØ¯ Ø´Ø§Ø´Ø© Ø¨Ø¯Ø§ÙŠØ© Ø£ØµÙ„ÙŠØ© ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‹Ø§


  # ðŸ“„ Ù…Ø¤Ø´Ø±Ø§Øª Ø§Ù„ØµÙØ­Ø§Øª
  smooth_page_indicator: ^1.2.1        # Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø¤Ø´Ø±Ø§Øª Ù„Ù„ØµÙØ­Ø§Øª Ø§Ù„Ù…ØªÙ†Ù‚Ù„Ø© (PageView)
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3

  flutter_localization: ^0.3.2
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0                # Ù‚ÙˆØ§Ø¹Ø¯ ØªØ­Ø³ÙŠÙ† Ø§Ù„ÙƒÙˆØ¯ ÙˆØ§Ù„ØªÙ†Ø¨ÙŠÙ‡ Ù„Ù„Ø£Ø®Ø·Ø§Ø¡

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/daily_quotes.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300


    - family: Tajawal
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

# Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø´Ø§Ø´Ø© Ø§Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø£ÙˆÙ„ÙŠØ© (Splash Screen)
flutter_native_splash:
  color: "#e7e8e3"
  image: "assets/images/Logo22.png"
  android: true
  ios: true
  web: false

# Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ (Launcher Icon)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_background: "#e7e8e3"
  adaptive_icon_foreground: "assets/images/logo1.png"
